# Generated by Django 5.2 on 2025-06-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Initialization'), ('in_progress', 'In_progress'), ('finished', 'Finished')], default='init', max_length=15),
        ),
    ]
