# Generated by Django 5.2 on 2025-08-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='app_run.athleteinfo'),
        ),
    ]
