# Generated by Django 5.2 on 2025-06-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_athleteinfo_goals_alter_athleteinfo_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
