# Generated by Django 5.2 on 2025-08-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_alter_position_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_run.run'),
        ),
    ]
