# Generated by Django 5.2 on 2025-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_position_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
