# Generated by Django 5.2 on 2025-08-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_collectibleitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectibleItems',
            new_name='CollectibleItem',
        ),
    ]
