# Generated by Django 5.2 on 2025-09-05 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_rename_collectibleitems_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='collected_by',
            field=models.ManyToManyField(blank=True, related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
