# Generated by Django 5.2 on 2025-09-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_collectibleitem_collected_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='collected_by',
            new_name='user',
        ),
    ]
