# Generated by Django 5.2 on 2025-09-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_rename_collected_by_collectibleitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='user',
            new_name='collected_by',
        ),
    ]
