# Generated by Django 5.2 on 2025-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0019_alter_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
