# Generated by Django 5.2 on 2025-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_alter_collectibleitem_uid_alter_position_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
