# Generated by Django 5.2 on 2025-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_run_distance_alter_position_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('value', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('picture', models.URLField()),
            ],
        ),
    ]
