# Generated by Django 5.2 on 2025-07-10 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='item',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
