# Generated by Django 5.2 on 2025-07-10 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_collectibleitem_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='item',
            field=models.ManyToManyField(related_name='collectibleItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
