# Generated by Django 5.2 on 2025-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
