# Generated by Django 5.2 on 2025-07-10 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_alter_collectibleitem_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='item',
            field=models.ManyToManyField(related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
