# Generated by Django 5.2 on 2025-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
