# Generated by Django 5.2 on 2025-07-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0026_alter_collectibleitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='item',
            new_name='collected_by',
        ),
    ]
