# Generated by Django 5.2 on 2025-07-13 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0027_rename_item_collectibleitem_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
