# Generated by Django 5.2 on 2025-07-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0028_position_data_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
