# Generated by Django 5.2 on 2025-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0029_rename_data_time_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
