# Generated by Django 5.2 on 2025-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0030_alter_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
