# Generated by Django 5.2 on 2025-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0031_position_speed_run_average_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
