# Generated by Django 5.2 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0032_position_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
