# Generated by Django 5.2 on 2025-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0033_alter_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
