# Generated by Django 5.2 on 2025-07-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0034_alter_position_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='distance',
        ),
    ]
