# Generated by Django 5.2 on 2025-07-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0036_run_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='average_speed',
            new_name='speed',
        ),
    ]
