# Generated by Django 5.2 on 2025-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0038_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
